Simplest code to visualise the robot workspace, doesn't consider self collisions.


In [74]:
import numpy as np
from numpy.linalg import inv
import modern_robotics as mr

In [75]:
#let's give the kinematics description of serial robot
M = np.array([[1., 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0.29],
              [0, 0, 0, 1]])
Slist = np.array([[0,   0,      0,         0,          0,                 1],
                  [0,   1,      1,         0,          1,                 0],
                  [1,   0,      0,         1,          0,                 0],
                  [0,   -0.09, -(0.09+0.1),-0.074,    0.265,              0.0],
                  [0,    0,     0. ,       0.034,      0.0,             0.268],
                  [0,   -0.04, -0.04,      0,        -0.04,               0]])
# thetalist = np.array([0.,np.pi/4.,-np.pi/4, np.pi/4,0.,0.])
thetalist = np.array([0.,0.,0.,0.,0.,0.])
thetalist


array([0., 0., 0., 0., 0., 0.])

In [76]:
# direct kinematics test
T = mr.FKinSpace(M, Slist, thetalist)
print('T=',T)

T= [[1.   0.   0.   0.  ]
 [0.   1.   0.   0.  ]
 [0.   0.   1.   0.29]
 [0.   0.   0.   1.  ]]


In [77]:
#inverse kinematics test
thetalist0 = np.array([0.8, 1.5, -1.2, 0.8, 0.9, 0.3]) #init guess
thetalist_init = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
eomg = 0.01
ev = 0.001
inv_res = mr.IKinSpace(Slist, M, T, thetalist0, eomg, ev)
inv_res

(array([  4.63410936, -19.06058737,  20.46584636, -23.54901362,
          6.36033363,  11.16160969]),
 True)

### The workspace tracking concept
To check the workspace of manipulator we define some assamptions.
1. The tool has such orientation that the output axis is perpendicular to horizontal plane(base flatform).
2. The first axis of manipulator is verical one(perpendicular to horizontal plane)
3. The home configuration(zero configuration) of manipulator is vetical aligned (candle).



In [78]:
#take 100 points in space around the base for end-effector
set_of_T = []
set_of_angles = np.linspace(0, 359, 120)[:-1]
# set_of_angles
for angle in set_of_angles:
    thetalist = np.array([angle,np.pi/2.,0.,0.,-np.pi/2.,0.])
    T = mr.FKinSpace(M, Slist, thetalist)
    set_of_T.append(T)

## Visualization part

In [82]:
import chart_studio.plotly as py
import plotly.graph_objects as go
# plotly.tools.set_credentials_file(username='xmlpro100', api_key='4gZPSqQbOAJh8IYI4NtK')

In [83]:
x_data = []
y_data = []
z_data = []
for item in set_of_T:
    tx, ty, tz = item[0,3], item[1,3], item[2,3]
    x_data.append(tx)
    y_data.append(ty)
    z_data.append(tz)
print('x max,min', max(x_data), min(x_data))
print('y max,min', max(y_data), min(y_data))
print('z max,min', max(z_data), min(z_data))

x max,min 0.35475691981249136 -0.35500000000000004
y max,min 0.3540450442634097 -0.3549899302566987
z max,min 0.6449999999999999 0.6449999999999999


In [84]:
# just draw
x, y, z = x_data, y_data, z_data

fig = go.Figure(data=[go.Scatter3d(x=x, y=y, z=z,
                                   mode='markers',
    marker=dict(
        size=12,
        color=z,                # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    ))])
fig.show()